blueprint:
  name: STYRBAR – Plafonnier CCT (mémoire jour/nuit + rampe douce)
  domain: automation
  description: >
    Pilotage d’un plafonnier CCT avec STYRBAR.
    Mémoire jour/nuit, rampe douce, HOLD luminosité et CCT.

  input:
    remote_action:
      name: Capteur d’actions STYRBAR
      selector:
        entity:
          domain: sensor

    light_entity:
      name: Plafonnier
      selector:
        entity:
          domain: light

    fade_in_seconds:
      name: Durée rampe d’allumage
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: secondes

    day_brightness_mem:
      name: Mémoire luminosité jour
      selector:
        entity:
          domain: input_number

    day_ct_mem:
      name: Mémoire CCT jour
      selector:
        entity:
          domain: input_number

    night_brightness_mem:
      name: Mémoire luminosité nuit
      selector:
        entity:
          domain: input_number

    night_ct_mem:
      name: Mémoire CCT nuit
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id: !input remote_action

variables:
  is_night: "{{ is_state('sun.sun', 'below_horizon') }}"
  mem_brightness_entity: "{{ night_brightness_mem if is_night else day_brightness_mem }}"
  mem_ct_entity: "{{ night_ct_mem if is_night else day_ct_mem }}"
  brightness_step: 10
  ct_step: 8
  min_ct: 153
  max_ct: 370
  delay_ms: 200

action:
  - choose:

      # 🔆 ALLUMAGE
      - conditions: "{{ trigger.to_state.state == 'brightness_move_up' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness: "{{ states(mem_brightness_entity) | int(omit) }}"
              color_temp: "{{ states(mem_ct_entity) | int(omit) }}"
              transition: !input fade_in_seconds

      # 🌑 EXTINCTION
      - conditions: "{{ trigger.to_state.state == 'brightness_move_down' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity

      # 🔆 HOLD UP
      - conditions: "{{ trigger.to_state.state == 'brightness_move_up_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input remote_action
                  state: brightness_move_up_hold
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    brightness_step: "{{ brightness_step }}"
                - delay:
                    milliseconds: "{{ delay_ms }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ mem_brightness_entity }}"
              value: "{{ state_attr(!input light_entity, 'brightness') }}"

      # 🌈 HOLD CCT
      - conditions: >
          {{ trigger.to_state.state in ['arrow_left_hold', 'arrow_right_hold'] }}
        sequence:
          - variables:
              direction: "{{ -1 if trigger.to_state.state == 'arrow_left_hold' else 1 }}"
          - repeat:
              while:
                - condition: state
                  entity_id: !input remote_action
                  state: "{{ trigger.to_state.state }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity
                  data:
                    color_temp_step: "{{ ct_step * direction }}"
                - delay:
                    milliseconds: "{{ delay_ms }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ mem_ct_entity }}"
              value: "{{ state_attr(!input light_entity, 'color_temp') }}"
